{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openpsirt.serviceAccountName" . }}
  labels: {{- include "openpsirt.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
# Nothing in openpsirt talks to the Kubernetes API.
automountServiceAccountToken: false
{{- end }}
