package migrations

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/pressly/goose/v3"

	"github.com/bhouse-nexthop/openpsirt/internal/database"
	"github.com/bhouse-nexthop/openpsirt/internal/database/migrate"
)

func init() {
	goose.AddMigrationContext(upCatalogue, downCatalogue)
}

// What a scan can be filed against: a product, one of its streams, and a
// variant of that stream. All three are declared before anything may target
// them, so a mistyped name is rejected rather than quietly creating a stream
// that looks real (ING-11).
//
// Branches and tags share a table. They differ only in that a branch moves and
// a tag never does, and everything else about them is the same — a product,
// variants, findings, an end-of-life date (MDL-17).
func upCatalogue(ctx context.Context, tx *sql.Tx) error {
	e := migrate.EngineFrom(ctx)
	t := typesFor(e)
	if t == nil {
		return fmt.Errorf("no schema for %s", e)
	}

	statements := []string{
		`CREATE TABLE product (
			id           ` + t.id + `,
			name         ` + t.name + ` NOT NULL,
			display_name ` + t.text + ` NOT NULL,
			eol_on       ` + t.date + ` NULL,
			created_at   ` + t.timestamp + ` NOT NULL,
			CONSTRAINT product_name_unique UNIQUE (name)
		)` + t.suffix,

		// kind is 'branch' or 'tag'. parent_id is the branch a tag was cut
		// from, when that is known.
		`CREATE TABLE stream (
			id         ` + t.id + `,
			product_id ` + t.ref + ` NOT NULL,
			name       ` + t.name + ` NOT NULL,
			kind       ` + t.kind + ` NOT NULL,
			parent_id  ` + t.refNull + ` NULL,
			eol_on     ` + t.date + ` NULL,
			created_at ` + t.timestamp + ` NOT NULL,
			CONSTRAINT stream_name_unique UNIQUE (product_id, name),
			CONSTRAINT stream_product_fk FOREIGN KEY (product_id) REFERENCES product (id),
			CONSTRAINT stream_parent_fk  FOREIGN KEY (parent_id)  REFERENCES stream (id)
		)` + t.suffix,

		// A variant belongs to a stream, not to the product: one added in a
		// later release must not appear to have existed in earlier ones
		// (MDL-01).
		//
		// customer_facing feeds ranking, and defaults true because an
		// unclassified artifact should rank as though it ships (ING-09).
		`CREATE TABLE variant (
			id              ` + t.id + `,
			stream_id       ` + t.ref + ` NOT NULL,
			name            ` + t.name + ` NOT NULL,
			customer_facing ` + t.boolean + ` NOT NULL,
			created_at      ` + t.timestamp + ` NOT NULL,
			CONSTRAINT variant_name_unique UNIQUE (stream_id, name),
			CONSTRAINT variant_stream_fk FOREIGN KEY (stream_id) REFERENCES stream (id)
		)` + t.suffix,

		`CREATE INDEX stream_product_idx ON stream (product_id)`,
		`CREATE INDEX variant_stream_idx ON variant (stream_id)`,
	}

	for _, stmt := range statements {
		if _, err := tx.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("%s: %w", firstLine(stmt), err)
		}
	}
	return nil
}

func downCatalogue(ctx context.Context, tx *sql.Tx) error {
	for _, table := range []string{"variant", "stream", "product"} {
		if _, err := tx.ExecContext(ctx, `DROP TABLE `+table); err != nil {
			return err
		}
	}
	return nil
}

// columnTypes holds the spellings that differ between engines. Everything the
// application queries is portable; only the declarations are not.
type columnTypes struct {
	id        string // primary key, generated
	ref       string // foreign key column
	refNull   string // nullable foreign key column
	name      string // short identifier, indexed and compared
	text      string // free text
	date      string // a calendar date
	timestamp string // a moment
	boolean   string
	kind      string
	suffix    string
}

func typesFor(e database.Engine) *columnTypes {
	switch e {
	case database.Postgres:
		return &columnTypes{
			id: "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", ref: "BIGINT", refNull: "BIGINT",
			name: "VARCHAR(191)", text: "TEXT", date: "DATE", timestamp: "TIMESTAMPTZ",
			boolean: "BOOLEAN", kind: "VARCHAR(16)",
		}
	case database.MySQL, database.MariaDB:
		// 191 keeps a unique key inside the index limit on older servers using
		// a four-byte character set.
		return &columnTypes{
			id: "BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY", ref: "BIGINT", refNull: "BIGINT",
			name: "VARCHAR(191)", text: "TEXT", date: "DATE", timestamp: "DATETIME(6)",
			boolean: "TINYINT(1)", kind: "VARCHAR(16)",
			suffix: " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
		}
	case database.SQLite:
		// DATETIME, not TEXT: the driver decides how to return a value from
		// the declared type, and TEXT will not scan into a time.Time.
		return &columnTypes{
			id: "INTEGER PRIMARY KEY AUTOINCREMENT", ref: "INTEGER", refNull: "INTEGER",
			name: "TEXT", text: "TEXT", date: "DATE", timestamp: "DATETIME",
			boolean: "BOOLEAN", kind: "TEXT",
		}
	}
	return nil
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i > 0 {
		return strings.TrimSpace(s[:i])
	}
	return strings.TrimSpace(s)
}
